title: OncoPearls
description: High-yield oncology pearls & resources by Dr. Rishabh Jain (@drrishabhonco)

remote_theme: just-the-docs/just-the-docs

# Required for remote theme to work
plugins:
  - jekyll-remote-theme

color_scheme: light
search_enabled: true
heading_anchors: true

aux_links:
  "Follow on X": "https://x.com/drrishabhonco"
  "GitHub Repo": "https://github.com/drrishabhonco/OncoPearls"
