title: OncoPearls
description: High-yield oncology pearls & trial summaries by Dr. Rishabh Jain (@drrishabhonco)

remote_theme: just-the-docs/just-the-docs

color_scheme: light
search_enabled: true
heading_anchors: true

aux_links:
  "Follow on X": "https://x.com/drrishabhonco"
  "GitHub Repo": "https://github.com/drrishabhonco/OncoPearls"

footer_content: "Made with ❤️ for oncology residents & DM students"